model:
  module: "dummymodel"
  class: "Random"

training:
  loss:
    module_loss_function: "torch.nn"
    class_loss_function: "L1Loss"
  optimizer: 
    module_optimizer: "torch.optim"
    class_optimizer: "Adam"
    parameters:
      lr: 0.001  