model:
  module: "model_definition"
  class: "UNet"

training:
  loss:
    module_loss_function: "torch.nn"
    class_loss_function: "L1Loss"
  optimizer: 
    module_optimizer: "torch.optim"
    class_optimizer: "Adam"
    parameters:
      lr: 0.001
metrics:
  - name: "psnr"          # Nombre de la métrica
    module: "validation_metrics"    # Módulo donde se encuentra la métrica
    class: "compute_psnr"         # Clase de la métrica
    parameters: {}
  - name: "mse"          # Nombre de la métrica
    module: "validation_metrics"    # Módulo donde se encuentra la métrica
    class: "compute_mse"         # Clase de la métrica
    parameters: {}
  
  