name: Python application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install onnx
        pip install pyyaml
        pip install torch
        pip install torchvision
        pip install torchaudio
        pip install imageio
        pip install pytorch-lightning
        pip install --upgrade torch torchvision
        pip install onnxruntime pillow numpy
        pip install tensorflow
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Test specific file with pytest
      run: |
        pytest src/test_generic_training/generic_training_test.py
