# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
    paths:
      - src/export_step/**
  pull_request:
    branches: [ "main" ]
    paths:
      - src/export_step/**

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest onnx pyyaml torch torchvision torchaudio imageio pytorch-lightning \
                   onnxruntime pillow numpy tensorflow
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run tests for generic_training_test.py
      run: |
        pytest src/test_export_onnx/export_test.py
